#ifndef ZEPHYR_DRIVERS_SENSOR_SCD41_H_
#define ZEPHYR_DRIVERS_SENSOR_SCD41_H_

#include <zephyr/types.h>
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/i2c.h>


#define DT_DRV_COMPAT sensiron_scd41

#define SCD41_BUS_I2C DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
#define SCD41_I2C_ADDR_62 (0x62)


struct i2c_dt_spec i2c;

typedef int (*scd41_bus_check_fn)(struct i2c *bus);
typedef int (*scd41_reg_read_fn)(struct i2c *bus,
				  uint8_t start, uint8_t *buf, int size);
typedef int (*scd41_reg_write_fn)(struct i2c *bus,
				   uint8_t reg, uint8_t val);


struct scd41_bus_io {
	scd41_bus_check_fn check;
	scd41_reg_read_fn read;
	scd41_reg_write_fn write;
};


typedef enum {
    SCD4X_START_PERIODIC_MEASUREMENT_CMD_ID = 0x21b1,
    SCD4X_READ_MEASUREMENT_RAW_CMD_ID = 0xec05,
    SCD4X_STOP_PERIODIC_MEASUREMENT_CMD_ID = 0x3f86,
    SCD4X_SET_TEMPERATURE_OFFSET_RAW_CMD_ID = 0x241d,
    SCD4X_GET_TEMPERATURE_OFFSET_RAW_CMD_ID = 0x2318,
    SCD4X_SET_SENSOR_ALTITUDE_CMD_ID = 0x2427,
    SCD4X_GET_SENSOR_ALTITUDE_CMD_ID = 0x2322,
    SCD4X_SET_AMBIENT_PRESSURE_RAW_CMD_ID = 0xe000,
    SCD4X_GET_AMBIENT_PRESSURE_RAW_CMD_ID = 0xe000,
    SCD4X_PERFORM_FORCED_RECALIBRATION_CMD_ID = 0x362f,
    SCD4X_SET_AUTOMATIC_SELF_CALIBRATION_ENABLED_CMD_ID = 0x2416,
    SCD4X_GET_AUTOMATIC_SELF_CALIBRATION_ENABLED_CMD_ID = 0x2313,
    SCD4X_SET_AUTOMATIC_SELF_CALIBRATION_TARGET_CMD_ID = 0x243a,
    SCD4X_GET_AUTOMATIC_SELF_CALIBRATION_TARGET_CMD_ID = 0x233f,
    SCD4X_START_LOW_POWER_PERIODIC_MEASUREMENT_CMD_ID = 0x21ac,
    SCD4X_GET_DATA_READY_STATUS_RAW_CMD_ID = 0xe4b8,
    SCD4X_PERSIST_SETTINGS_CMD_ID = 0x3615,
    SCD4X_GET_SERIAL_NUMBER_CMD_ID = 0x3682,
    SCD4X_PERFORM_SELF_TEST_CMD_ID = 0x3639,
    SCD4X_PERFORM_FACTORY_RESET_CMD_ID = 0x3632,
    SCD4X_REINIT_CMD_ID = 0x3646,
    SCD4X_GET_SENSOR_VARIANT_RAW_CMD_ID = 0x202f,
    SCD4X_MEASURE_SINGLE_SHOT_CMD_ID = 0x219d,
    SCD4X_MEASURE_SINGLE_SHOT_RHT_ONLY_CMD_ID = 0x2196,
    SCD4X_POWER_DOWN_CMD_ID = 0x36e0,
    SCD4X_WAKE_UP_CMD_ID = 0x36f6,
    SCD4X_SET_AUTOMATIC_SELF_CALIBRATION_INITIAL_PERIOD_CMD_ID = 0x2445,
    SCD4X_GET_AUTOMATIC_SELF_CALIBRATION_INITIAL_PERIOD_CMD_ID = 0x2340,
    SCD4X_SET_AUTOMATIC_SELF_CALIBRATION_STANDARD_PERIOD_CMD_ID = 0x244e,
    SCD4X_GET_AUTOMATIC_SELF_CALIBRATION_STANDARD_PERIOD_CMD_ID = 0x234b,
} SCD4X_CMD_ID;

typedef enum {
    SCD4X_SENSOR_VARIANT_MASK = 0xF000,
    SCD4X_SENSOR_VARIANT_SCD40 = 0x0000,
    SCD4X_SENSOR_VARIANT_SCD41 = 0x1000,
    SCD4X_SENSOR_VARIANT_SCD42 = 0x2000,
    SCD4X_SENSOR_VARIANT_SCD43 = 0x5000,
} scd4x_sensor_variant;


#endif /*ZEPHYR_DRIVERS_SENSOR_SCD41_H_*/
